name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.0.0)"
        required: true
      prerelease:
        description: "Mark as pre-release?"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prepare version info
      - name: Set version variables
        id: vars
        run: |
          if [ "${{ github.event.inputs.prerelease }}" == "true" ]; then
            echo "TAG=v${{ github.event.inputs.version }}-pre" >> $GITHUB_ENV
            echo "TITLE=Pre-Release v${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "FILENAME_SUFFIX=Pre-Release" >> $GITHUB_ENV
          else
            echo "TAG=v${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "TITLE=Release v${{ github.event.inputs.version }}" >> $GITHUB_ENV
            echo "FILENAME_SUFFIX=Release" >> $GITHUB_ENV
          fi

      # Create ZIP archive
      - name: Create ZIP package
        run: |
          zip -r "project_${FILENAME_SUFFIX}_${{ github.event.inputs.version }}.zip" . -x "*.git*"

      # Create 7z archive
      - name: Create 7Z package
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full
          7z a "project_${FILENAME_SUFFIX}_${{ github.event.inputs.version }}.7z" . -xr'!.git'

      # Upload both archives to release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TITLE }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            project_${{ env.FILENAME_SUFFIX }}_${{ github.event.inputs.version }}.zip
            project_${{ env.FILENAME_SUFFIX }}_${{ github.event.inputs.version }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
