name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
      prerelease:
        description: 'Mark as pre-release? (true/false)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release suffix
        id: release_suffix
        run: |
          if [ "${{ github.event.inputs.prerelease }}" == "true" ]; then
            echo "SUFFIX=-pre" >> $GITHUB_ENV
          else
            echo "SUFFIX=" >> $GITHUB_ENV
          fi

      - name: Create zip file
        run: |
          zip -r myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.zip .

      - name: Create 7z file
        run: |
          7z a myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.7z .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4 # Changed from v3 to v4
        with:
          name: myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}
          path: |
            myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.zip
            myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.7z

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4 # Changed from v3 to v4
        with:
          name: myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}${{ env.SUFFIX }}
          name: Release ${{ github.event.inputs.version }}${{ env.SUFFIX }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.zip
            myproject_${{ github.event.inputs.version }}${{ env.SUFFIX }}.7z
