name: Bundle Scripts for Release

on:
  push:
    paths:
      - 'Scripts/**'  # Trigger on changes to the 'Scripts' folder

jobs:
  bundle-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bundle scripts for release
        run: |
          zip -r release.zip ./Scripts/*

      - name: Rename zip file
        run: mv release.zip ScriptsBundle.zip

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-zip
          path: ScriptsBundle.zip

  create-release:
    needs: bundle-scripts
    runs-on: ubuntu-latest

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v2
        with:
          name: release-zip
          path: release-artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }} - Scripts Bundle
          draft: false
          prerelease: false
          body: |
            Automatic release triggered by changes to files in the 'Scripts' folder.

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-artifacts/ScriptsBundle.zip
          asset_name: ScriptsBundle.zip
          asset_content_type: application/zip
